from collections.abc import Iterator
from typing_extensions import Self

CRLF: str
QUOTATION: dict[str, str]

def split(text: str, separator: str, crlf: bool = True) -> list[str]: ...
def split_once(text: str, separator: str, crlf: bool = True) -> tuple[str, str]: ...
def split_once_without_escape(text: str, separator: str, crlf: bool = True) -> tuple[str, str]: ...
def split_once_index_only(text: str, separator: str, offset: int, crlf: bool = True): ...

class String(Iterator[str]):
    left_index: int
    offset: int
    next_index: int
    len: int
    text: str

    def __init__(self, text: str): ...
    def step(self, separator: str, crlf: bool = True) -> None: ...
    def val(self) -> str: ...
    def apply(self, left: int = -1): ...
    def rest(self) -> str: ...
    def reset(self) -> None: ...
    @property
    def complete(self) -> bool: ...
    @property
    def will_complete(self) -> bool: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> str: ...
