name: Test & Track
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        py_ver: ['3.8', '3.9', '3.10', '3.11']
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        name: Ensure Python Runtime
        with:
          python-version: ${{matrix.py_ver}}
          architecture: 'x64'
      - name: Set Environment Variables
        run: |
          export TARINA_NO_EXTENSIONS=1
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm
      - name: Install Package
        run: |
          pdm sync -G:all
      - name: Install self
        run: |
          pdm install
      - name: Test & Report
        run: |
          pdm run test