name: Test & Track
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/build.yml'
      - '.github/workflows/auto-merge.yml'
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        py_ver: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        name: Ensure Python Runtime
        with:
          python-version: ${{matrix.py_ver}}
          architecture: 'x64'
      - name: Ensure PDM
        run: |
          python3 -m pip install pdm
      - name: Install Package
        run: |
          pdm sync -G:all --no-self
      - name: Install self
        run: |
          export TARINA_NO_EXTENSIONS=1 && pdm install
      - name: Test & Report
        run: |
          pdm run test

  test_with_extensions:
    strategy:
      matrix:
        py_ver: ['3.9', '3.10', '3.11', '3.12', '3.13']
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        name: Ensure Python Runtime
        with:
          python-version: ${{matrix.py_ver}}
          architecture: 'x64'
      - name: Ensure PDM
        run: |
          python3 -m pip install pdm
      - name: Install Package
        run: |
          pdm sync -G:all --no-self
      - name: Cythonize
        run: |
          pdm run make
      - name: Install self
        run: |
          pdm install -v
      - name: Test & Report
        run: |
          pdm run test